plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.3'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'org.jetbrains.kotlin.jvm'
	id 'maven-publish'
}

group = 'com'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}
bootJar {
	enabled = false
}

jar {
	enabled = true
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifactId = 'SecLib'

			versionMapping {
				usage('java-api') {
					fromResolutionOf('runtimeClasspath')
				}
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
		}
	}
	repositories {
		mavenLocal()
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.h2database:h2'
	implementation 'jakarta.validation:jakarta.validation-api:3.1.0-M1'
	implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
	implementation 'jakarta.el:jakarta.el-api:6.0.0-RC1'
	implementation 'org.springframework.security:spring-security-crypto:6.2.2'
	implementation 'org.glassfish:jakarta.el:4.0.2'
	implementation 'org.bouncycastle:bcprov-jdk18on:1.77'
	implementation 'jakarta.servlet:jakarta.servlet-api:6.1.0-M2'
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
	implementation 'org.jboss.aerogear:aerogear-otp-java:1.0.0'
	implementation 'org.springframework:spring-web'
	implementation 'org.springframework:spring-webmvc'
	implementation 'com.google.zxing:core:3.5.3'
	implementation 'com.google.zxing:javase:3.5.2'
	implementation  group: 'com.googlecode.owasp-java-html-sanitizer', name: 'owasp-java-html-sanitizer', version: '20240325.1'
	implementation 'org.mapstruct:mapstruct:1.6.0'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'
	implementation 'org.springframework:spring-webmvc:6.1.12'
	implementation 'org.apache.httpcomponents:httpclient:4.5.14'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
	implementation 'com.auth0:java-jwt:3.18.1'
	implementation 'com.nimbusds:nimbus-jose-jwt:9.40'
	implementation 'org.springframework.session:spring-session-core:3.3.2'
}

tasks.named('test') {
	useJUnitPlatform()
}
kotlin {
	jvmToolchain(21)
}

tasks.register('cleanBuildPublish') {
	dependsOn 'clean', 'build', 'publishToMavenLocal'
}

sourceSets {
	main {
		java {
			srcDirs += ['generated']
		}
	}
}
